### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#1]
Can you create  a page to hold a simple new page for an FAQ please Matt? 

In Welsh call it "Holi Heliwm" 
In Eng call it "Ask Heliwm"

For the URL use heliwm.com/holi

I want a single link that I can share in the emails instead of the Support pages. 

Thanks

**Comment by MattHall** [comment]
Added. Just need content for the two files now.

**Comment by nwdls** [comment]
@MattHall Is this deployed at https://staging.heliwm.com/cy/holi ?

The EN version seems to go somewhere: https://staging.heliwm.com/en/holi
