### ISSUE TITLE
Admin Backers Page - What do the different cancellation options do?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#10]
There's a dropdown on the right hand side of each back with options: unconfirm backer, refund backer, refund and hide, cancel backer, delete backer. 
 
It would be good to clarify what each of these do and whether we need them all after removing the credits system.

**Comment by MattHall** [comment]
Unconfirm: Will mark the backer as not confirmed.
Refund: Will perform a refund on the back, then mark the back as refunded
Refund and hide: Seems to just mark the back as refunded and cancelled - doesn't actually perform a refund from what I can see
cancel: Just transitions to cancelled. No refund performed
delete: marks the back as deleted. 

Only backs marked as 'confirmed', 'requested_refund', 'refunded', or 'waiting_confirmation' are displayed on the frontend.

**Comment by nwdls** [comment]
Thanks Matt. I can't see the reason for having Refund and Hide in there then. Could you remove it please, just to avoid confusion?

**Comment by nwdls** [comment]
Thanks.
