### ISSUE TITLE
Seems like users should be able to upload a lead image - why is this option not there?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#104]
Is it display_image or project_image? 

The code in the app/views/projects/backers/edit.html.slim page looks for an image for the project to display but there is no way of uploading an image from the project page. 

If there are functions of the website which use and image then maybe this should be reinstated?

FAO @iestynx  also

**Comment by MattHall** [comment]
Odd - it's not on the create project page, but it is under the edit tab on the project view: https://staging.heliwm.com/cy/TotallyAwesomeBoingyThing#edit

I'll add it in.

**Comment by nwdls** [comment]
Thanks. Seems like it doesn't show anywhere except as a thumbnail image for the project, replacing the one taken from YT / Vimeo.
