### ISSUE TITLE
Project Page - Error when changing video 

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#12]
Got an error when trying to change a video on a project page

**Comment by MattHall** [comment]
For bugs like this, having accurate recreation steps is a real help - it prevents me from having to try different things if I'm having trouble recreating. For bugs in general, include an overall description of the bug, steps to reproduce and ideally a sentence explaingin what happened, and one explaining what you expected to happen :)

**Comment by MattHall** [comment]
Not been able to reproduce so far :cry:

**Comment by nwdls** [comment]
Hmm, just tried myself and it worked. Let's close it for now and if it happens again, I'll try to be more accurate about replicating.
