### ISSUE TITLE
How are recent projects ordered?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#120]
It seems like the projects in recent are ordered a bit randomly. Can you explain what parameter they use to order them?

See here: Mega Boing was created before Totally Awesome and Super Mega
![screen shot 2015-07-08 at 11 44 20](https://cloud.githubusercontent.com/assets/1568316/8568587/e00f8e50-2566-11e5-9ab2-a24b9960ae77.png)

**Comment by MattHall** [comment]
expiring: expires_at desc
recent: online_date desc
ended_success: expires_at desc
ended_failure: expires_at desc

**Comment by nwdls** [comment]
I may well have put them online in that order. Ta.
