### ISSUE TITLE
Re-design Backers/Edit (backer detail submission form) Page

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#122]
https://staging.heliwm.com/en/projects/[project number]/backers/[back number]/edit

Remove the first h1 text. 
Move the project thumbnail somehwere sensible. 
Tidy up the rest!
Incorporate amendments in issue #110

**Comment by iestynx** [comment]
sgen ti screen grab o hwn?

**Comment by nwdls** [comment]
@iestynx ![screen shot 2015-07-10 at 23 59 52](https://cloud.githubusercontent.com/assets/1568316/8630609/e2d5415c-275f-11e5-9e20-4a419bdc5581.png)

**Comment by nwdls** [comment]
Screengrab rong...
Hwn di'r un iawn:
![screen shot 2015-07-10 at 23 58 43](https://cloud.githubusercontent.com/assets/1568316/8630694/06109d00-2761-11e5-96e4-29fdaef7dd2f.png)
![screen shot 2015-07-10 at 23 58 55](https://cloud.githubusercontent.com/assets/1568316/8630696/0960c408-2761-11e5-982a-4be15d84b0a3.png)

**Comment by nwdls** [comment]
Os ti'm isio newid y bit gwaelod ormod, jest rhoi un h1 efo "Talu gyda Stripe". 

Gormod o h1 sdwff o gwmpas y lle falle? Ma na ticket arall ar gyfer y county field

**Comment by iestynx** [comment]
yn passable am rwan, dal angen neud y form yn well ond mae'r layout mymryn yn well

**Comment by nwdls** [comment]
Diolch. Gwneud gwahaniaeth.
