### ISSUE TITLE
Emails - None sent out to backers

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#13]
Need to test again. Was it looking for a cy and en translated file?

**Comment by nwdls** [comment]
@MattHall just tested this with a back from the admin acount and two backs from the tester@example.com account in both EN and CY but no emails have come through to letter opener. Can you confirm that this is fixed please?

**Comment by MattHall** [comment]
@nwdls OK, deployed and tested this. Looks to be working now.
