### ISSUE TITLE
Is this link markup correct?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#17]
Want to change:

Cymraeg Para saber tudo sobre como estruturar o seu projeto, baixe o #{link_to 'Guia Completo', "#{Configuration[:base_url]}/guia_realizadores.pdf", target: '_blank'}".html_safe

to...

#{link_to 'Holi Heliwm', "#http://heliwm.com/cy/holi", target: '_blank'}".html_safe

Taken from 

app/views/projects/_project_edit.cy.html.slim

**Comment by MattHall** [comment]
No need for the # in the url:
```
#{link_to 'Holi Heliwm', "http://heliwm.com/cy/holi", target: '_blank'}".html_safe
```
and if you're linking to the faq page, you can do:
```
#{link_to 'Holi Heliwm', faq_page_path, target: '_blank'}".html_safe
```

**Comment by nwdls** [comment]
When project pages are working again, need to check whether the markup was correct
