### ISSUE TITLE
Can you help me with a little cock up?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#19]
I've been translating files for the last hour and putting them in the feature/translation tree https://github.com/meigwilym/cytarse/tree/feature/translations/app/views/projects rather than the master tree https://github.com/meigwilym/cytarse/tree/master/app/views/projects

Is there a simple way of transferring them. I've no idea how that happened...

**Comment by nwdls** [comment]
Just manually copied most of them but then the commit button was greyed out. Were you deploying maybe? Just the successful_warning left to do now.

**Comment by MattHall** [comment]
If you've already transferred them across, then I'd say just stick with that. I could have rebased the translations then merged, but probably too late now :sweat_smile: This ticket may be closable unless there is anything else?

**Comment by nwdls** [comment]
Yes, they've all moved across. Thanks.
