### ISSUE TITLE
Awaiting Fund Warning - Question

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#20]
As the Stripe payments are essentially promises, I guess this awaiting funds warning won't appear, and so doesn't need translating? Am i right?

https://github.com/meigwilym/cytarse/blob/master/app/views/projects/_waiting_funds_warning.cy.html.slim

**Comment by MattHall** [comment]
Yeah, it looks like we should never get to a state where we have backers in the 'waiting_confirmation' state, so this won;t need translation.

**Comment by nwdls** [comment]
Great. Thanks for confirming.
