### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#21]
Would it be possible to create a blank contact page please? 

@iestynx Is a contact form best practice or do we just have a blurb and email? Could you offer some guidance on this please? Ta

**Comment by MattHall** [comment]
Added. Just need to know where you want this linking. Pages are here: 
https://github.com/meigwilym/cytarse/blob/master/app/views/static/contact.en.html.slim
https://github.com/meigwilym/cytarse/blob/master/app/views/static/contact.cy.html.slim

**Comment by nwdls** [comment]
Just to the EN: "contact"  CY: "Cyswllt" links on the footer at present please. Thanks

**Comment by nwdls** [comment]
Thanks @MattHall 

@iestynx Could you advise on whether we should have a contact form (spam protected?) or just an email address and other contact details.

**Comment by iestynx** [comment]
You could be fine with just the email address to begin with, but if it really takes off it would be best to have a structured contact form so that the emails are categorised.

**Comment by nwdls** [comment]
Ok, will keep it as a simple page. Might dress it up later! Diolch
