### ISSUE TITLE
2 Check Boxes when creating a project

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#23]
The T&Cs note that:

![image](https://cloud.githubusercontent.com/assets/1568316/6464777/8ae7f4e6-c1b4-11e4-8671-0bb8228518fa.png)

So we will need two mandatory checkboxes to tick prior to submitting a project draft. 

@iestynx there might be design issues arising to follow this

**Comment by MattHall** [comment]
@nwdls Could I just get the following text from you (in en and cy):

1. Text to appear next to the 'authorize Heliwm to store and use producers details' checkbox.
2. Text to appear next to 'I am 18' checkbox
3. Error message text for both checkboxes if left unchecked and the for is submitted

**Comment by nwdls** [comment]
I've added in the third checkbox statement. 

EN
1. I authorise Heliwm to store and use my details according to the Privacy and Cookie Policy
2. I am aged 18 or over
3. I am resident or have my principal place of business in the UK
3. You must agree to the statements and tick all boxes in order to continue

CY
1. Rwyf yn caniatáu i Heliwm gadw a defnyddio fy manylion yn unol â'r polisi preifatrwydd a chwcis
2. Rwyf yn 18 oed neu'n hŷn
3. Rwyf yn byw neu gyda fy lleoliad busnes arferol o fewn y DU 
4. Rhaid cytuno i'r gosodiadau a thicio'r tri blwch er mwyn parhau
