### ISSUE TITLE
Only 2 live projects allowed per producer

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#24]
The T&Cs have flagged this up: 

![image](https://cloud.githubusercontent.com/assets/1568316/6464833/eda84cd4-c1b4-11e4-862e-128766c39057.png)

Is this something that we manage through blocking, or just human monitoring at assessment stage? If it's a simple fix then we'll go for the blocking, but if it is at all complicated then just add it in as a feature on the wish list for the time being.

**Comment by MattHall** [comment]
I've added something that will only let a user have 2 projects associated with their account at any one time. There is nothing to stop a user creating many accounts though, so human checks should still be done.

**Comment by nwdls** [comment]
Excellent thanks Matt. I think this will work for now as we will not have many people initially creating more than two drafts.
