### ISSUE TITLE
Large Embed Image needs Heliwm Logo 

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#30]
![screen shot 2015-03-04 at 14 20 07](https://cloud.githubusercontent.com/assets/1568316/6485195/de07ae1c-c279-11e4-99a9-66ff0f9e6a51.png)

Taken from: https://staging.heliwm.com/cy/Test5-MoIPIssues#about

**Comment by iestynx** [comment]
Matt, the image is embedded, can you swap it for the one I've putt in /cytarse/public/assets/heliwm/svg/heliwm-logo-dark.svg

**Comment by nwdls** [comment]
Great. Thanks.
