### ISSUE TITLE
404 on TestProject4 on EN side

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#31]
Got a 404 here: https://staging.heliwm.com/en/Test4-CampaignCancelled 

I clicked on it from the DIscover page https://staging.heliwm.com/en/darganfod

But it works ok in CY https://staging.heliwm.com/cy/Test4-CampaignCancelled

(Is it a 404? Not sure! ;)

**Comment by MattHall** [comment]
Are you logged in at all? I've just visited that link while logged out, and it seemed to work fine

**Comment by nwdls** [comment]
I may have been logged out.

Just tried it when logged in as a non-admin user and it worked (though I
don't know who I was logged in as!), didn't when logged out.

Tried it when logged in as admin@example.com and the error occurs again.
Same when logged in as rhodri.apdyfrig@gmail.com



2015-03-04 22:36 GMT+00:00 Matt Hall <notifications@github.com>:

**Comment by MattHall** [comment]
Pushed a fix for this - can you verify please?

**Comment by nwdls** [comment]
Looks good to me. Thanks
