### ISSUE TITLE
Reset password warning CY issue

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#33]
When attempting to reset password the warning pop-up says the reset link has expired. The email is sent out as it has appeared in LetterOpener.

This might be a mistranslation or it might be a bug. Not sure. I'll check

**Comment by nwdls** [comment]
This is a bug. 

Checked the translations and the string is being fetched from 'failure: password_token' rather than 'confirmations: send_instructions'

However, the password reset email is still going out ok https://staging.heliwm.com/letter_opener/1435278967_5d07f7b/rich

Can you check why this is please Matt?

Thanks

**Comment by MattHall** [comment]
Just tested this, and it seems to be working fine. Could you just confirm?

**Comment by nwdls** [comment]
I think I may have mistranslated it... translated. will close after checking at next commit.
