### ISSUE TITLE
There's no asterisk next to the password label to denote a required field when registering

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#37]
**Steps to reproduce:**

1. When logged out go to https://staging.heliwm.com/cy/ymuno

**Expected result**

There's an asterisk next to the required fields to show that they're not optional.

**Actual result**

There's no asterisk next to the password field but there is one next to the email field.

![image](https://cloud.githubusercontent.com/assets/3416991/6562245/c501a6b2-c697-11e4-99d6-407eecdd27d1.png)

**Comment by iestynx** [comment]
Matt - this has a class of "optional" can you take a look at it please?

**Comment by nwdls** [comment]
@MattHall could look at this one as well please? Thanks
