### ISSUE TITLE
After registering in Welsh the user is redirected to the English home page

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#38]
**Steps to reproduce:**

1. When logged out, go to https://staging.heliwm.com/cy/ymuno
2. Enter a valid email and password
3. Click 'Cofrestru'

**Expected result:**

The new  user is created, logged in and taken to https://staging.heliwm.com/cy

**Actual result:**

The new user is created, logged in but taken to https://staging.heliwm.com/en

**Comment by nwdls** [comment]
Thanks Maredudd. I thought that I was having a problem with this too. Could you check this out please @MattHall
