### ISSUE TITLE
Error messages in English when incorrectly logging in on the Welsh login page

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#39]
**Steps to reproduce:**

1. When logged out go to the login page
2. Click "Mewngofnodi"

**Expected result:**

An error pops up under the email field telling the user to fill in the field in Welsh.

** Actual result:**

The error message is in English.

**Other connected errors**

The messages are also in English if an invalid email is entered.

![image](https://cloud.githubusercontent.com/assets/3416991/6562401/31bf747c-c699-11e4-8e3b-9dd2238b2421.png)

![image](https://cloud.githubusercontent.com/assets/3416991/6562406/3b9f4788-c699-11e4-9168-3b9800e751ad.png)

**Comment by nwdls** [comment]
I've searched the code for those strings but don't get any results. @MattHall could you help me find them so I can translate please?

**Comment by MattHall** [comment]
These errors are styled and translated by the browser, not cytarse, so we don't have much control. If you set your browser language to Welsh, then the correct strings should appear.

Alternatively, I can turn off html5 validation for form fields, if that makes things a little more consistent. Let me know!

**Comment by nwdls** [comment]
@MattHall Thanks. Please leave them as they are. If people complain then at least we know what to tell them!
