### ISSUE TITLE
Adolygu testun Cymraeg: "caru fo"

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#41]
I fi mae'r geiriau 'caru fo' yn y frawddeg hon yn swnio braidd fel bratiaith:

"rydyn ni'n caru fo pan mae pobl eisiau gwneud yn lle dweud! "

Bydden i'n argymhell "rydyn ni'n ei garu pan fod pob eisiau gwneud yn lle dweud".   Ond efallai fy mod yn hollol anghywir ac ei fod yn well fel y mae.

**Comment by maredudd** [comment]
Ar y dudalen hon: https://staging.heliwm.com/cy/canllaw_dechrau

**Comment by nwdls** [comment]
Diolch.
