### ISSUE TITLE
Camgym testun: er mwyn i roi'r cyfle gorau

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#42]
Tudalen: https://staging.heliwm.com/cy/canllaw_dechrau

Mae'n dweud "er mwyn i roi'r cyfle gorau" ond dylai ddweud "er mwyn rhoi'r cyfle gorau".

**Comment by nwdls** [comment]
@maredudd ie, mae na lot o bethau fel'na. Un drafft o gyfieithu dwi wedi gwneud felly os ti'n gweld rhywbeth tafla nhw atai. Diolch
