### ISSUE TITLE
Camgym testun: amser mynd a'r proseict yn fyw

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#43]
Tudalen: https://staging.heliwm.com/cy/canllaw_dechrau

Mae'n dweud:
```amser mynd a'r proseict yn fyw```

Mae dau gamgymeriad a dylai ddweud:

```amser mynd â'r prosiect yn fyw```

**Comment by maredudd** [comment]
Yn yr un man mae'n dweud `hn` yn lle `hon` a `barid` yn lle `barod`

**Comment by maredudd** [comment]
Hefyd `yterfyn` yn lle `y terfyn`

**Comment by nwdls** [comment]
Wedi'u cywiro. Diolch
