### ISSUE TITLE
Text larger than the containing box

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#45]
**Steps to reproduce:**

1. Log into the Welsh pages
2. Click to submit project

The background to the area listing the requirements to create a project does not cover the whole text and the formatting of the text itself seems a bit strange with to much space between the lines of text.  This is a problem in both the Welsh and English versions:

![image](https://cloud.githubusercontent.com/assets/3416991/6570914/6a2afe62-c702-11e4-83c0-d50cf22320f6.png)

![image](https://cloud.githubusercontent.com/assets/3416991/6570894/0ad11802-c702-11e4-8c6a-011bfec16702.png)

**Comment by nwdls** [comment]
@maredudd This is a known issue because the new design by @iestynx  hasn't been implemented here yet. I'll close this issue for now. Diolch
