### ISSUE TITLE
Admin Financials - No details on "i" icon click

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#5]
![screen shot 2015-02-24paymentadminpage](https://cloud.githubusercontent.com/assets/1568316/6431776/835078a2-c033-11e4-96c4-a9dea0fc1458.png)

**Comment by MattHall** [comment]
This is related to the pending payments. Before a backer selects a payment method, it creates their payment and sets it to pending. We can either:
1. Ignore these pending backs - treat pending backs as incomplete. You may want to chase them up if they complete some of the form.
2. Add an additional filter to prevent pending backs from being displayed

Which would you prefer, @nwdls ?

**Comment by nwdls** [comment]
I'm not sure if I would chase up on them tbh. You never know why people would step back from a back and I wouldn't want to push. Go for 1.
Thanks

**Comment by MattHall** [comment]
@nwdls Are we OK to close this ticket?

**Comment by nwdls** [comment]
Yep
