### ISSUE TITLE
Where can I translate the Stripe Gateway text?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#50]
![screen shot 2015-03-11 at 10 18 09](https://cloud.githubusercontent.com/assets/1568316/6594309/fefbf4f8-c7d7-11e4-8b22-de177bf6ee9b.png)

I can't seem to find it by searching Git

**Comment by MattHall** [comment]
I've invited you to the catarse_stripe repo. Locale files are here: https://github.com/Codebeef/catarse_stripe/tree/master/config/locales

**Comment by nwdls** [comment]
I've translated them but they don't seem to have appeared yet on the Stripe Auth page upon Clicking authorise https://staging.heliwm.com/payment/stripe/auth 

@MattHall ?

**Comment by MattHall** [comment]
I need to update the gem in this project and deploy before the changes are visible. I recently deployed, so these should be there now, though it looks like there are a few keys missing. Check the differences between the cy and en files in the locales on the other repo, and add the missing ones to the cy locale.

**Comment by nwdls** [comment]
Done this now. Cheers for pointing that out. Will check it after next deploy.

**Comment by nwdls** [comment]
I'm still getting English text here: https://staging.heliwm.com/cy/payment/stripe/auth

Are we talking about the same pages? Not sure!

**Comment by MattHall** [comment]
Just updating the gem and deploying now...

**Comment by MattHall** [comment]
OK, deployed.
