### ISSUE TITLE
Admin Area - Followers section - what is it for?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#53]
It shows a blank page when clicked at present.
![screen shot 2015-03-11 at 10 51 53](https://cloud.githubusercontent.com/assets/1568316/6594875/c5f4273e-c7dc-11e4-9e3a-d6ab921ab844.png)

Link: https://staging.heliwm.com/en/admin/followers

**Comment by MattHall** [comment]
@nwdls There doesn't appear to be any controller or templates associated with that route. Shall I remove the link?

**Comment by nwdls** [comment]
@MattHall Yes please!
