### ISSUE TITLE
None of the successful projects appearing in 'successful' search

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#56]
See: https://staging.heliwm.com/en/darganfod#successful

These project should appear there 
https://staging.heliwm.com/en/Test1-TargetReached
https://staging.heliwm.com/en/Test5-MoIPIssues

Is it because they are awaiting funds or something like that?

**Comment by MattHall** [comment]
Looks to be an issue with the cron task. I've reset the command when I deployed, and it looks to be running normally now. If you could create another successful project, I'll check again tomorrow to be sure it's updating the projects correctly.

**Comment by nwdls** [comment]
@MattHall Great thanks for this.
