### ISSUE TITLE
Stripe Connection Issue

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#6]
After connecting to Stripe for the first time it takes you to your profile page rather than back to the create project page

**Comment by MattHall** [comment]
The confirmation page that shows after you connect your account has a "Back To User" button. Clicking this returns you to your profile. Would changing this button to link to the new project page and updating the text to 'Create my first project' work for you? @nwdls

**Comment by nwdls** [comment]
That would be great. 
Thanks.

**Comment by nwdls** [comment]
I just assigned you back...is this how this works? :)

**Comment by MattHall** [comment]
@nwdls Yeah, just assign away - I'll assign to you if I'm waiting on your response or @-mention you if it's just information

**Comment by nwdls** [comment]
Thanks. This might be revisited after user testing but will close for now.
