### ISSUE TITLE
No asterisk next to all required fields when creating a project

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#61]
**Steps to reproduce**

1. Log in
2. Go to https://staging.heliwm.com/en/projects/new
3. Fill in all fields with an asterisk to denote that it's required (Project URL, List Project Related Links, List Your First Backers, 
4. Click the 'Save Draft' button.

**Expected Result**

A draft of the project is created.

**Actual Result**

The project will not be created due to a required field not filled in.  If that field is filled in and the form is submitted again then there's another field that is required, and so on.  The labels of all these fields need to have an asterisk.

**Comment by nwdls** [comment]
Iestyn, can you add this in please?

**Comment by iestynx** [comment]
@MattHall can you make it possible for me to create projects please? The only things I can't finish is the stuff to set up a project. I've created a Stripe account and tried connecting, but then hangs on a blank white screen.
Ta

**Comment by iestynx** [comment]
@nwdls these look like they're hard coded in the cy.yml can you go through them and add them where they need to be?

**Comment by nwdls** [comment]
Done this now. Left the final boxes as unstarred so that they can be filled during drafting stage
