### ISSUE TITLE
Some of the fields marked as required are optional

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#62]
**Steps to reproduce**

1. Log in
2. Go to https://staging.heliwm.com/en/projects/new
3. Fill in the project url, project's name, about your project, punchline and how much do you intend to raise fields.
4. Click the 'Save Draft' button.

**Expected Result**

A draft of the project is not created.  The form is shown with errors to denote that the fields shown as required (list project related links, list your first backers) are not populated.

**Actual Result**

A draft of the project is created.

**Comment by nwdls** [comment]
When Stripe is back working create a new account to test this.
