### ISSUE TITLE
Error in admin if accessing a draft project in Welsh

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#63]
**Steps to reproduce**

1. Log in as admin with the Welsh UI.
2. Go to Projects (https://staging.heliwm.com/cy/admin/projects)
3. Click on a project which has a status of draft

**Expected result**

The project page is opened.

**Actual result**

The error page is shown:

![image](https://cloud.githubusercontent.com/assets/3416991/6650899/1420f17c-ca2a-11e4-9bb1-370086ae505f.png)

**Comment by nwdls** [comment]
@MattHall Thanks
