### ISSUE TITLE
On project page a space is left for a video when there's no video to show

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#64]
**Steps to reproduce**

1. Create a project without a video
2. Go to the project page for the new project

There's a big empty space where a video would be:

![image](https://cloud.githubusercontent.com/assets/3416991/6650909/da9188d0-ca2a-11e4-8950-a178d831e781.png)

**Comment by nwdls** [comment]
All projects have to have a video so the field should be made compulsory. 

@MattHall Can you change this please? Thanks This is also related to issue #62

**Comment by nwdls** [comment]
Also added * to the form on cy.yml
