### ISSUE TITLE
Email server timezone is EDT instead of the same timezone as Wales

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#69]
The mail server's timezone is set to EDT instead of the Welsh timezone so it's about 5 hours behind.

**Comment by MattHall** [comment]
This is an effect of using letter opener; it's using the modified time of the tmp files used to store the emails on disk as the sent time. This won't be an issue when we come to send emails in production.

**Comment by nwdls** [comment]
Thanks @MattHall
