### ISSUE TITLE
Admin Page - Users not showing correctly

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#7]
Admin page - different users all show as 'Nao preenchido' although they go to the right user profile when clicked https://staging.heliwm.com/cy/admin/financials

**Comment by MattHall** [comment]
This looks to be trying to display the Moip login:
```ruby
(project.user.moip_login.blank? ? 'Não preenchido' : project.user.moip_login)
```
... But the link goes to the user settings. I could use the users email or name as an alternative - would that be OK? @nwdls

**Comment by nwdls** [comment]
Usernames instead would be great.

**Comment by nwdls** [comment]
The users on this page are all still showing as Nao Preenchido though? Am I missing something here? Could you just clarify what has changed please Matt?

**Comment by MattHall** [comment]
I was using the nickname rather than the display name - looks like it should have been the display name. Fixed and deployed.

**Comment by nwdls** [comment]
@MattHall excellent. Thanks
