### ISSUE TITLE
No confirmation email sent after backing a project

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#70]
**Steps to reproduce**

1. Log in
2. Find any project
3. Back the project by any amount.

**Expected behaviour**

An email is sent confirming that you have backed the project.

**Actual behaviour**

No email is sent.

**Comment by maredudd** [comment]
I'm looking at the email logs to test this.  There are no emails actually sent out.  I'm presuming that this is because it's in a test mode.  Is that correct, or should I actually be receiving emails?

**Comment by nwdls** [comment]
I'll close this issue as it's a duplicate of #13
