### ISSUE TITLE
Missing text strings on user project pages (and error on deleted project page?)

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#71]
I created a duplicate project, deleted in admin, still visible in user Profile page. 

It looks like it's supposed to be visible to the user, however there's missing text strings. Can you tell me where these are located @MattHall ?

Is it here? https://github.com/meigwilym/cytarse/blob/Rhodri/app/models/project.rb 

Project was created by user tester@example.com
Project name test 8 April 30
![screen shot 2015-04-30 at 16 48 21](https://cloud.githubusercontent.com/assets/1568316/7416634/c4d70f26-ef58-11e4-83e6-d81ad8d796b3.png)

**Comment by MattHall** [comment]
Looks like those strings were missing. I've added them in this commit: 7720b22fa5e5d05a9a8321dc5c126c4bd062eba7

**Comment by nwdls** [comment]
Translated in Master.
