### ISSUE TITLE
"My Facebook" - can't find where the string is to edit the text!

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#73]
It's located on the user profile settings page https://staging.heliwm.com/cy/users/20-tester-account#settings

I want to change "My Facebook" but can't for the life of me find where .my_facebook referrs back to to retrieve 'My Facebook'. 

(The intro to Ruby course was obviously no good...)

**Comment by MattHall** [comment]
I've added the missing key here: a54beeba698a7f52c6269ba6b8a0ab62db7dfdd7
