### ISSUE TITLE
Stripe Account Setup - Should there (can there?) be a Heliwm logo at the top?

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#74]
![screen shot 2015-06-26 at 01 05 21](https://cloud.githubusercontent.com/assets/1568316/8368235/8ac1e7ca-1b9f-11e5-84d3-2064e25bef40.png)

**Comment by MattHall** [comment]
Yeah, looks to be possible - if you can send me a square logo to attach, I'll add it.

**Comment by nwdls** [comment]
Great. Here you go. 
![heliwm-logo-02](https://cloud.githubusercontent.com/assets/1568316/8441689/c16c1e96-1f71-11e5-9dac-c4c4dff85653.png)

**Comment by MattHall** [comment]
Added to the account

**Comment by nwdls** [comment]
Ace.
