### ISSUE TITLE
Problem with Stripe authenticatio in dev mode. 

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#75]
Action: created new user (tester2@example.com); was prompted to create Stripe account, clicked yes setup; clicked 'Skip this account form' 

Expected result: Return to user profile with Stripe connection made

Actual result: blank screen at https://staging.heliwm.com/payment/stripe/callback?scope=read_write&code=ac_6UjybbOAFYmtpWGF2deuUdqPjOfeFwQT#

**Comment by MattHall** [comment]
This is fixed on staging

**Comment by nwdls** [comment]
Great. Just tested with user tester10. Worked fine. Thanks.
