### ISSUE TITLE
Can't create new project - Warning Strap: can't have more than 2 projects in draft

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#78]
Using tester@example.com user

Tried to create a new project.

Warning strap came up across the bottom of the screen to say that you can't create a new project if you have 2 projects either in draft or in process. This account has none in draft and only successful / failed projects.

**Comment by MattHall** [comment]
Ah think this is an issue with wording the original ticket (https://github.com/meigwilym/cytarse/issues/24) added the check on number of online or waiting for completion projects, not drafts. We can either change the wording (no more than N projects on the site at one time) or we can change the rule to apply to only drafts (a user could then have > N projects live on the site).

**Comment by nwdls** [comment]
@MattHall Ah ok. That makes sense. So what is the trigger for the transaction to be completed then? Is it awaiting funds cleared through Stripe? Can you explain the flow a bit more to me?

If it is currently not allowing more than 2 **live** projects at any one time, then that is fine. We should just change the wording of the warning to say "you may not have nore than two live projects".

**Comment by nwdls** [comment]
@MattHall Just checked on this now and there should be a way for projects which are 'online' (so displayed as 'awaiting confirmation') to be set as successful. The Brazilian setup needed to allow some work to check funds etc and leave 3 days to do this, but in our case I think we should make it much more straightforward. A simple check by admin then press a button next to the project. 

On the project admin page https://staging.heliwm.com/en/admin/projects there's a dropdown next to each project but all it allows admin to do is 'save to draft'. Has an option disappeared from here? e.g. accept/reject project?

**Comment by nwdls** [comment]
So there should be dropdown options from can_remove and can_reject but they're not showing?

**Comment by maredudd** [comment]
#85 has been created to cover the problem with the missing dropdown statuses.

**Comment by MattHall** [comment]
Has the text of the flash message been changed for this ticket? If so, can we close and take any related issues up in separate tickets?

**Comment by nwdls** [comment]
@MattHall I haven't amended the text. Can you tell me where to find them please?

**Comment by nwdls** [comment]
Just translated amended them.
