### ISSUE TITLE
Heliwm seems to think 2 projects 'are in their final days'

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#79]
Opened letter opener to check email for new member (tester2@example.com)

https://staging.heliwm.com/letter_opener/1435276963_eb9d42b/rich

The welcome email has a section saying: 

##For starters, it is worth knowing three projects that are in the final days:

The two projects shown are: 
aksmdlkasmdlkm https://staging.heliwm.com/en/tester123
AND
test8 30 April https://staging.heliwm.com/en/test8 

This might also be caused by the same problems as with issue #78

**Comment by MattHall** [comment]
The cron job should be running hourly now.
