### ISSUE TITLE
Server error is in Welsh on English site

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#80]
When there's a server error in the English website the error message is shown in Welsh with the following message:

"Rydyn ni'n cael peth trafferth. Mae'r criw technegol wedi cael gwybod am hyn ac yn brysur yn ceisio adfer y sefyllfa. Ceisia eto mewn munud neu ddau."

Currently an example of this can be seen at https://staging.heliwm.com/en/termau due to a bug on that page.  I'm not sure how to reproduce this error page once that page is fixed.

**Comment by MattHall** [comment]
Looks to be a slim template error - investigating now.

```
ActionView::Template::Error (Malformed indentation
  /home/app/heliwm_staging/releases/20150630205818/app/views/static/terms.html.slim, Line 161, Column 1
```

**Comment by MattHall** [comment]
I've added localized error pages here 0b099c6aae1d09615f2d3d28a53b21a2a4035f8e

The 404 and 422 pages need the layout copying from the 500 error and the error messages updating accordingly.
