### ISSUE TITLE
Warnings text at top of project page before submitting for evaluation is badly formatted

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#84]
*Steps to reproduce*

1. Log in
2. Create a new project
3. Go the the project page (you'll be taken there automatically after project creation.  The URL has is similar to https://staging.heliwm.com/en/gari

The text at the top of the page is badly formatted, see image.

![screen shot 2015-06-30 at 22 58 24](https://cloud.githubusercontent.com/assets/3416991/8443145/1249fa22-1f7c-11e5-98cb-8e422fa10718.png)

**Comment by nwdls** [comment]
I deleted some stuff I shouldn't have...

**Comment by nwdls** [comment]
Note: located here https://github.com/meigwilym/cytarse/tree/master/app/views/projects

**Comment by nwdls** [comment]
Ones that need correcting: 

CY
~~Analysis~~
~~Draft~~
Online
Rejected
Successful
Waiting Funds

EN
~~Analysis~~
~~Draft~~
Online
Rejected
Successful
Waiting Funds
