### ISSUE TITLE
When creating a new account in CY locale; welcome email is in EN

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#86]
Created a new profile in CY locale (tester12). Checked the email sent out and it's in EN. Can you look to fix the locale that it points to please?

**Comment by nwdls** [comment]
@MattHall Trying to test this but getting a failed page load on both CY and EN sides of https://staging.heliwm.com/cy/ymuno

**Comment by nwdls** [comment]
Getting CY emails for creating a project but still getting an EN email after the project has been accepted and gone live. See https://staging.heliwm.com/letter_opener/1436225623_b41596f/rich

**Comment by MattHall** [comment]
I've removed the debug causing the error on the signup page. Will look at the locale issue this evening.

**Comment by MattHall** [comment]
The CY email on creating a project is due to there being no template for the CY locale. I've renamed the current template and added a new one here (222125c5527178b9d24d8bf2e8943e5acf430f7c):  app/views/catarse_bootstrap/notifications_mailer/project_visible.cy.html.slim

**Comment by nwdls** [comment]
Great, just translated it. Ready for next deploy.
