### ISSUE TITLE
Backing a project - collecting user address

### ISSUE THREAD

**Issue by nwdls** [meigwilym/cytarse#9]
Address field has to be mandatory when paying sending a reward. 

Currently the address is in Brazilian format with a checkbox. 

All backers must be based within the EU (need to double check on this).

**Comment by MattHall** [comment]
I've made the address always visible, which in turn makes it always required. I've removed he Brazilian format for the zipcode and deleted the 'live in brazil?' checkbox. Let me know if there is anything further you need for this ticket.

**Comment by nwdls** [comment]
Thanks for that. A few issues. 

![screen shot 2015-03-04 at 14 45 57](https://cloud.githubusercontent.com/assets/1568316/6485661/38e61b18-c27d-11e4-9772-2c589220d2a9.png)

There's some odd stuff going on with address_complement (see image)

- Can we remove the address_neighbourhood field.
- Can we remove the address_number field. 
- Can we add a second address_street field (not compulsory)
- Can we add a third address_street field (not compulsory)
- Can we name the address fields - Address 1, Address 2, Address 3
- Can we remove the mobile phone number field.
- Can we change the address_state field to just County allowing free text.
- Can we add a a country field
- Can we add a note at the bottom stating that funds are only accepted from within the EU.

Cheers (this may need reviewing again in future)

**Comment by nwdls** [comment]
FYI Stripe is only available for use in the following countries according to the Stripe Payment Gateway connection page 

![screen shot 2015-03-04 at 15 02 04](https://cloud.githubusercontent.com/assets/1568316/6486000/b857c87c-c27f-11e4-8476-64ae2f919232.png)

Maybe we could just put these in a dropdown list and make them compulsory?

**Comment by MattHall** [comment]
Working on this - it's a bit more involved than expected as the address is hooked into the reporting via views in the database.

**Comment by nwdls** [comment]
Ok, thanks. Are the address details on user profiles linked in as well I
wonder?

2015-03-04 22:32 GMT+00:00 Matt Hall <notifications@github.com>:

**Comment by MattHall** [comment]
@nwdls For the county in the address fields, if we have it as a freeform entry, then the 'Nearby' functionality will not work correctly (subtle differences in spelling or punctuation would mean that the names don't match). 

I've just about completed the address change, so will push to staging as soon as I can.

**Comment by nwdls** [comment]
@MattHall I think the nearby functionality can be deprecated then. We would have to create something different for each country for which Stripe is accepted.  I don't think it's particularly useful when our target is Wales anyway. It might have been different for Brazil! Could you change this please? Thanks

**Comment by MattHall** [comment]
@nwdls Just so I'm sure what you'd like to have done here, could you open a new ticket please with the details of what you'd like changing? Thanks!
